<?php

use Illuminate\Database\Seeder;
use \Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["display_name" => "Afghanistan", "code" => "AF"],
            ["display_name" => "Åland Islands", "code" => "AX"],
            ["display_name" => "Albania", "code" => "AL"],
            ["display_name" => "Algeria", "code" => "DZ"],
            ["display_name" => "American Samoa", "code" => "AS"],
            ["display_name" => "Andorra", "code" => "AD"],
            ["display_name" => "Angola", "code" => "AO"],
            ["display_name" => "Anguilla", "code" => "AI"],
            ["display_name" => "Antarctica", "code" => "AQ"],
            ["display_name" => "Antigua and Barbuda", "code" => "AG"],
            ["display_name" => "Argentina", "code" => "AR"],
            ["display_name" => "Armenia", "code" => "AM"],
            ["display_name" => "Aruba", "code" => "AW"],
            ["display_name" => "Australia", "code" => "AU"],
            ["display_name" => "Austria", "code" => "AT"],
            ["display_name" => "Azerbaijan", "code" => "AZ"],
            ["display_name" => "Bahamas", "code" => "BS"],
            ["display_name" => "Bahrain", "code" => "BH"],
            ["display_name" => "Bangladesh", "code" => "BD"],
            ["display_name" => "Barbados", "code" => "BB"],
            ["display_name" => "Belarus", "code" => "BY"],
            ["display_name" => "Belgium", "code" => "BE"],
            ["display_name" => "Belize", "code" => "BZ"],
            ["display_name" => "Benin", "code" => "BJ"],
            ["display_name" => "Bermuda", "code" => "BM"],
            ["display_name" => "Bhutan", "code" => "BT"],
            ["display_name" => "Bolivia", "code" => "BO"],
            ["display_name" => "Bosnia and Herzegovina", "code" => "BA"],
            ["display_name" => "Botswana", "code" => "BW"],
            ["display_name" => "Bouvet Island", "code" => "BV"],
            ["display_name" => "Brazil", "code" => "BR"],
            ["display_name" => "British Indian Ocean Territory", "code" => "IO"],
            ["display_name" => "Brunei Darussalam", "code" => "BN"],
            ["display_name" => "Bulgaria", "code" => "BG"],
            ["display_name" => "Burkina Faso", "code" => "BF"],
            ["display_name" => "Burundi", "code" => "BI"],
            ["display_name" => "Cambodia", "code" => "KH"],
            ["display_name" => "Cameroon", "code" => "CM"],
            ["display_name" => "Cape Verde", "code" => "CV"],
            ["display_name" => "Cayman Islands", "code" => "KY"],
            ["display_name" => "Central African Republic", "code" => "CF"],
            ["display_name" => "Chad", "code" => "TD"],
            ["display_name" => "Chile", "code" => "CL"],
            ["display_name" => "China", "code" => "CN"],
            ["display_name" => "Christmas Island", "code" => "CX"],
            ["display_name" => "Cocos (Keeling) Islands", "code" => "CC"],
            ["display_name" => "Colombia", "code" => "CO"],
            ["display_name" => "Comoros", "code" => "KM"],
            ["display_name" => "Congo", "code" => "CG"],
            ["display_name" => "Congo, The Democratic Republic of the", "code" => "CD"],
            ["display_name" => "Cook Islands", "code" => "CK"],
            ["display_name" => "Costa Rica", "code" => "CR"],
            ["display_name" => "Cote D'Ivoire", "code" => "CI"],
            ["display_name" => "Croatia", "code" => "HR"],
            ["display_name" => "Cuba", "code" => "CU"],
            ["display_name" => "Cyprus", "code" => "CY"],
            ["display_name" => "Czech Republic", "code" => "CZ"],
            ["display_name" => "Denmark", "code" => "DK"],
            ["display_name" => "Djibouti", "code" => "DJ"],
            ["display_name" => "Dominica", "code" => "DM"],
            ["display_name" => "Dominican Republic", "code" => "DO"],
            ["display_name" => "Ecuador", "code" => "EC"],
            ["display_name" => "Egypt", "code" => "EG"],
            ["display_name" => "El Salvador", "code" => "SV"],
            ["display_name" => "Equatorial Guinea", "code" => "GQ"],
            ["display_name" => "Eritrea", "code" => "ER"],
            ["display_name" => "Estonia", "code" => "EE"],
            ["display_name" => "Ethiopia", "code" => "ET"],
            ["display_name" => "Falkland Islands(Malvinas)", "code" => "FK"],
            ["display_name" => "Faroe Islands", "code" => "FO"],
            ["display_name" => "Fiji", "code" => "FJ"],
            ["display_name" => "Finland", "code" => "FI"],
            ["display_name" => "France", "code" => "FR"],
            ["display_name" => "French Guiana", "code" => "GF"],
            ["display_name" => "French Polynesia", "code" => "PF"],
            ["display_name" => "French Southern Territories", "code" => "TF"],
            ["display_name" => "Gabon", "code" => "GA"],
            ["display_name" => "Gambia", "code" => "GM"],
            ["display_name" => "Georgia", "code" => "GE"],
            ["display_name" => "Germany", "code" => "DE"],
            ["display_name" => "Ghana", "code" => "GH"],
            ["display_name" => "Gibraltar", "code" => "GI"],
            ["display_name" => "Greece", "code" => "GR"],
            ["display_name" => "Greenland", "code" => "GL"],
            ["display_name" => "Grenada", "code" => "GD"],
            ["display_name" => "Guadeloupe", "code" => "GP"],
            ["display_name" => "Guam", "code" => "GU"],
            ["display_name" => "Guatemala", "code" => "GT"],
            ["display_name" => "Guernsey", "code" => "GG"],
            ["display_name" => "Guinea", "code" => "GN"],
            ["display_name" => "Guinea - Bissau", "code" => "GW"],
            ["display_name" => "Guyana", "code" => "GY"],
            ["display_name" => "Haiti", "code" => "HT"],
            ["display_name" => "Heard Island and Mcdonald Islands", "code" => "HM"],
            ["display_name" => "Holy See(Vatican City State)", "code" => "VA"],
            ["display_name" => "Honduras", "code" => "HN"],
            ["display_name" => "Hong Kong", "code" => "HK"],
            ["display_name" => "Hungary", "code" => "HU"],
            ["display_name" => "Iceland", "code" => "IS"],
            ["display_name" => "India", "code" => "IN"],
            ["display_name" => "Indonesia", "code" => "ID"],
            ["display_name" => "Iran, Islamic Republic Of", "code" => "IR"],
            ["display_name" => "Iraq", "code" => "IQ"],
            ["display_name" => "Ireland", "code" => "IE"],
            ["display_name" => "Isle of Man", "code" => "IM"],
            ["display_name" => "Israel", "code" => "IL"],
            ["display_name" => "Italy", "code" => "IT"],
            ["display_name" => "Jamaica", "code" => "JM"],
            ["display_name" => "Japan", "code" => "JP"],
            ["display_name" => "Jersey", "code" => "JE"],
            ["display_name" => "Jordan", "code" => "JO"],
            ["display_name" => "Kazakhstan", "code" => "KZ"],
            ["display_name" => "Kenya", "code" => "KE"],
            ["display_name" => "Kiribati", "code" => "KI"],
            ["display_name" => "Korea, Democratic People's Republic of", "code" => "KP"],
            ["display_name" => "Korea, Republic of", "code" => "KR"],
            ["display_name" => "Kuwait", "code" => "KW"],
            ["display_name" => "Kyrgyzstan", "code" => "KG"],
            ["display_name" => "Lao People'S Democratic Republic", "code" => "LA"],
            ["display_name" => "Latvia", "code" => "LV"],
            ["display_name" => "Lebanon", "code" => "LB"],
            ["display_name" => "Lesotho", "code" => "LS"],
            ["display_name" => "Liberia", "code" => "LR"],
            ["display_name" => "Libyan Arab Jamahiriya", "code" => "LY"],
            ["display_name" => "Liechtenstein", "code" => "LI"],
            ["display_name" => "Lithuania", "code" => "LT"],
            ["display_name" => "Luxembourg", "code" => "LU"],
            ["display_name" => "Macao", "code" => "MO"],
            ["display_name" => "Macedonia, The Former Yugoslav Republic of", "code" => "MK"],
            ["display_name" => "Madagascar", "code" => "MG"],
            ["display_name" => "Malawi", "code" => "MW"],
            ["display_name" => "Malaysia", "code" => "MY"],
            ["display_name" => "Maldives", "code" => "MV"],
            ["display_name" => "Mali", "code" => "ML"],
            ["display_name" => "Malta", "code" => "MT"],
            ["display_name" => "Marshall Islands", "code" => "MH"],
            ["display_name" => "Martinique", "code" => "MQ"],
            ["display_name" => "Mauritania", "code" => "MR"],
            ["display_name" => "Mauritius", "code" => "MU"],
            ["display_name" => "Mayotte", "code" => "YT"],
            ["display_name" => "Mexico", "code" => "MX"],
            ["display_name" => "Micronesia, Federated States of", "code" => "FM"],
            ["display_name" => "Moldova, Republic of", "code" => "MD"],
            ["display_name" => "Monaco", "code" => "MC"],
            ["display_name" => "Mongolia", "code" => "MN"],
            ["display_name" => "Montserrat", "code" => "MS"],
            ["display_name" => "Morocco", "code" => "MA"],
            ["display_name" => "Mozambique", "code" => "MZ"],
            ["display_name" => "Myanmar", "code" => "MM"],
            ["display_name" => "Namibia", "code" => "NA"],
            ["display_name" => "Nauru", "code" => "NR"],
            ["display_name" => "Nepal", "code" => "NP"],
            ["display_name" => "Netherlands", "code" => "NL"],
            ["display_name" => "Netherlands Antilles", "code" => "AN"],
            ["display_name" => "New Caledonia", "code" => "NC"],
            ["display_name" => "New Zealand", "code" => "NZ"],
            ["display_name" => "Nicaragua", "code" => "NI"],
            ["display_name" => "Niger", "code" => "NE"],
            ["display_name" => "Nigeria", "code" => "NG"],
            ["display_name" => "Niue", "code" => "NU"],
            ["display_name" => "Norfolk Island", "code" => "NF"],
            ["display_name" => "Northern Mariana Islands", "code" => "MP"],
            ["display_name" => "Norway", "code" => "NO"],
            ["display_name" => "Oman", "code" => "OM"],
            ["display_name" => "Pakistan", "code" => "PK"],
            ["display_name" => "Palau", "code" => "PW"],
            ["display_name" => "Palestinian Territory, Occupied", "code" => "PS"],
            ["display_name" => "Panama", "code" => "PA"],
            ["display_name" => "Papua New Guinea", "code" => "PG"],
            ["display_name" => "Paraguay", "code" => "PY"],
            ["display_name" => "Peru", "code" => "PE"],
            ["display_name" => "Philippines", "code" => "PH"],
            ["display_name" => "Pitcairn", "code" => "PN"],
            ["display_name" => "Poland", "code" => "PL"],
            ["display_name" => "Portugal", "code" => "PT"],
            ["display_name" => "Puerto Rico", "code" => "PR"],
            ["display_name" => "Qatar", "code" => "QA"],
            ["display_name" => "Reunion", "code" => "RE"],
            ["display_name" => "Romania", "code" => "RO"],
            ["display_name" => "Russian Federation", "code" => "RU"],
            ["display_name" => "RWANDA", "code" => "RW"],
            ["display_name" => "Saint Helena", "code" => "SH"],
            ["display_name" => "Saint Kitts and Nevis", "code" => "KN"],
            ["display_name" => "Saint Lucia", "code" => "LC"],
            ["display_name" => "Saint Pierre and Miquelon", "code" => "PM"],
            ["display_name" => "Saint Vincent and the Grenadines", "code" => "VC"],
            ["display_name" => "Samoa", "code" => "WS"],
            ["display_name" => "San Marino", "code" => "SM"],
            ["display_name" => "Sao Tome and Principe", "code" => "ST"],
            ["display_name" => "Saudi Arabia", "code" => "SA"],
            ["display_name" => "Senegal", "code" => "SN"],
            ["display_name" => "Serbia and Montenegro", "code" => "CS"],
            ["display_name" => "Seychelles", "code" => "SC"],
            ["display_name" => "Sierra Leone", "code" => "SL"],
            ["display_name" => "Singapore", "code" => "SG"],
            ["display_name" => "Slovakia", "code" => "SK"],
            ["display_name" => "Slovenia", "code" => "SI"],
            ["display_name" => "Solomon Islands", "code" => "SB"],
            ["display_name" => "Somalia", "code" => "SO"],
            ["display_name" => "South Africa", "code" => "ZA"],
            ["display_name" => "South Georgia and the South Sandwich Islands", "code" => "GS"],
            ["display_name" => "Spain", "code" => "ES"],
            ["display_name" => "Sri Lanka", "code" => "LK"],
            ["display_name" => "Sudan", "code" => "SD"],
            ["display_name" => "Suriname", "code" => "SR"],
            ["display_name" => "Svalbard and Jan Mayen", "code" => "SJ"],
            ["display_name" => "Swaziland", "code" => "SZ"],
            ["display_name" => "Sweden", "code" => "SE"],
            ["display_name" => "Switzerland", "code" => "CH"],
            ["display_name" => "Syrian Arab Republic", "code" => "SY"],
            ["display_name" => "Taiwan, Province of China", "code" => "TW"],
            ["display_name" => "Tajikistan", "code" => "TJ"],
            ["display_name" => "Tanzania, United Republic of", "code" => "TZ"],
            ["display_name" => "Thailand", "code" => "TH"],
            ["display_name" => "Timor - Leste", "code" => "TL"],
            ["display_name" => "Togo", "code" => "TG"],
            ["display_name" => "Tokelau", "code" => "TK"],
            ["display_name" => "Tonga", "code" => "TO"],
            ["display_name" => "Trinidad and Tobago", "code" => "TT"],
            ["display_name" => "Tunisia", "code" => "TN"],
            ["display_name" => "Turkey", "code" => "TR"],
            ["display_name" => "Turkmenistan", "code" => "TM"],
            ["display_name" => "Turks and Caicos Islands", "code" => "TC"],
            ["display_name" => "Tuvalu", "code" => "TV"],
            ["display_name" => "Uganda", "code" => "UG"],
            ["display_name" => "Ukraine", "code" => "UA"],
            ["display_name" => "United Arab Emirates", "code" => "AE"],
            ["display_name" => "United Kingdom", "code" => "GB"],
            ["display_name" => "United States Minor Outlying Islands", "code" => "UM"],
            ["display_name" => "Uruguay", "code" => "UY"],
            ["display_name" => "Uzbekistan", "code" => "UZ"],
            ["display_name" => "Vanuatu", "code" => "VU"],
            ["display_name" => "Venezuela", "code" => "VE"],
            ["display_name" => "Viet Nam", "code" => "VN"],
            ["display_name" => "Virgin Islands, British", "code" => "VG"],
            ["display_name" => "Virgin Islands, U . S . ", "code" => "VI"],
            ["display_name" => "Wallis and Futuna", "code" => "WF"],
            ["display_name" => "Western Sahara", "code" => "EH"],
            ["display_name" => "Yemen", "code" => "YE"],
            ["display_name" => "Zambia", "code" => "ZM"],
            ["display_name" => "Zimbabwe", "code" => "ZW"]
        ];

        foreach ($countries as $item) {
            DB::table('countries')->insert([
                'code' => $item['code'],
                'name' => $item['display_name']
            ]);
        }
    }
}
